---

- hosts: nextcloud_instances

  vars:

    nextcloud_network: nextcloud_network
    nextcloud_volume_data: nextcloud_data
    nextcloud_env_file: /tmp/nextcloud.env

  pre_tasks:

  tasks:

    - name: Create environmental file
      template:
        src: "{{ playbook_dir }}/templates/nextcloud.env.j2"
        dest: "{{ nextcloud_env_file }}"

    - name: Create volume for Nextcloud container data
      become: yes
      docker_volume:
        name: "{{ nextcloud_volume_data }}"
        state: present

    - name: Start Nextcloud container
      become: yes
      docker_container:
        name: nextcloud
        image: nextcloud
        env_file: "{{ nextcloud_env_file }}"
        published_ports:
          - 8080:80
        recreate: yes
        state: started
        volumes:
          - "{{ nextcloud_volume_data }}:/var/www/html"
