---

- hosts: nextcloud_nodes

  vars:
    nextcloud_network: nextcloud_network

  pre_tasks:

    # - name: "Run pre-tasks"
    #   import_role:
    #     name: pre-tasks

    - name: Install Docker
      import_role:
        name: geerlingguy.docker

  tasks:

    - name: Create nextcloud data volume
      docker_volume:
        name: nextcloud_data

    - name: Start nextcloud container
      docker_container:
        name: nextcloud
        image: nextcloud
        env:
          # POSTGRES_DB: nextcloud
          # POSTGRES_USER: nextcloud
          POSTGRES_PASSWORD: 'n#xtcl0ud'
          POSTGRES_HOST: 127.0.0.1
          REDIS_HOST: 127.0.0.1
          REDIS_HOST_PORT : 6379
        state: present
        recreate: yes
        ports:
          - 8080:80
        volumes:
          - nextcloud_data:/var/www/html/