---

- name: Install and configure Nextcloud on nodes within the nextcloud_instances group
  
  hosts: nextcloud_instances

  vars:

    nextcloud_network: nextcloud_network
    nextcloud_volume_data: nextcloud_data
    nextcloud_env_file: /tmp/nextcloud.env

    nextcloud_service_name: nextcloud
    nextcloud_service_ports_http: 8080
    nextcloud_service_ports: [
      { label: http, value: "{{ nextcloud_service_ports_http }}" }
    ]

    nextcloud_image_name: nextcloud
    nextcloud_image_tag: latest

  pre_tasks:

  tasks:

    - name: "Unregister {{ nextcloud_service_name }} service with the local consul agent"
      consul:
        host: "{{ ansible_host }}"
        service_name: "{{ nextcloud_service_name }}-{{ item.value }}"
        service_port: "{{ item.value | int }}"
        service_address: "{{ ansible_host }}"
        state: absent
      loop: "{{ nextcloud_service_ports }}"
      when: service_consul_running

    - name: Create environmental file
      template:
        src: "{{ playbook_dir }}/templates/nextcloud.env.j2"
        dest: "{{ nextcloud_env_file }}"

    - name: Create volume for Nextcloud container data
      become: yes
      docker_volume:
        name: "{{ nextcloud_volume_data }}"
        force: yes
        state: present

    - name: Start Nextcloud container
      become: yes
      docker_container:
        name: nextcloud
        image: nextcloud
        env_file: "{{ nextcloud_env_file }}"
        published_ports:
          - 8080:80
        recreate: yes
        state: started
        volumes:
          - "{{ nextcloud_volume_data }}:/var/www/html"

    - name: "Register {{ nextcloud_service_name }} service with the local consul agent"
      consul:
        host: "{{ ansible_host }}"
        service_name: "{{ nextcloud_service_name }}-{{ item.value }}"
        service_port: "{{ item.value | int }}"
        service_address: "{{ ansible_host }}"
        state: present
      loop: "{{ nextcloud_service_ports }}"
      when: service_consul_running
