---

- hosts: postgres_instances

  vars:

  pre_tasks:

  tasks:

    - name: Start pgAdmin container
      become: yes
      docker_container:
        name: pgadmin
        image: dpage/pgadmin4
        env:
          PGADMIN_DEFAULT_EMAIL: "{{ nextcloud_user }}@mynextcloud.com"
          PGADMIN_DEFAULT_PASSWORD: "{{ nextcloud_password }}"
        published_ports:
          - 8888:80
        recreate: yes
        state: started

