---

- hosts: postgres_instances

  vars:


    postgres_maintenance_db: postgres
    postrgres_volume_data: postgres_data

  pre_tasks:

  tasks:

    - name: Create volume for PostgreSQL container data
      become: yes
      docker_volume:
        name: "{{ postrgres_volume_data }}"
        state: present

    - name: Start PostgreSQL container
      become: yes
      docker_container:
        name: postgres
        image: postgres
        env:
          POSTGRES_PASSWORD: "{{ nextcloud_password }}"
          POSTGRES_USER: "{{ postgres_admin_user }}"
          POSTGRES_DB: "{{ postgres_maintenance_db }}"
        published_ports:
          - 5432:5432
        recreate: yes
        state: started
        volumes:
          - "{{ postrgres_volume_data }}:/var/lib/postgresql/data"
