---

- hosts: nextcloud_nodes

  vars:
    nextcloud_network: nextcloud_network

  pre_tasks:

    # - name: "Run pre-tasks"
    #   import_role:
    #     name: pre-tasks

    - name: Install Docker
      import_role:
        name: geerlingguy.docker

  tasks:

    - name: Create postgres data volume
      docker_volume:
        name: postgres_data

    - name: Start postgres container
      docker_container:
        name: postgres
        image: postgres
        env:
          POSTGRES_PASSWORD: 'n#xtcl0ud'
        state: present
        recreate: yes
        exposed_ports:
          - 5432
        volumes:
          - postgres_data:/var/lib/postgresql/data
