---

- hosts: postgres_instances

  vars:

  pre_tasks:

  tasks:

    - name: Create postgres data volume
      docker_volume:
        name: postgres_data

    - name: Start postgres container
      docker_container:
        name: postgres
        image: postgres
        env:
          POSTGRES_PASSWORD: 'n#xtcl0ud'
        state: present
        recreate: yes
        exposed_ports:
          - 5432
        volumes:
          - postgres_data:/var/lib/postgresql/data
