---

- hosts: redis_instances

  vars:

  pre_tasks:

  tasks:

    - name: Create redis volume
      become: yes
      docker_volume:
        name: redis_data

    - name: Start redis container
      become: yes
      docker_container:
        name: redis
        image: redis
        command: redis-server --appendonly yes
        state: present
        recreate: yes
        exposed_ports:
          - 6379
        volumes_from:
          - redis_data
