---

- hosts: redis_instances

  vars:

    redis_volume_data: redis_data

  pre_tasks:

  tasks:

    - name: Create volume for Redis container data
      become: yes
      docker_volume:
        name: "{{ redis_volume_data }}"
        state: present

    - name: Start Redis container
      become: yes
      docker_container:
        name: redis
        image: redis
        command: redis-server --appendonly yes
        published_ports :
          - 6379:6379
        recreate: yes
        state: started
        volumes:
          - "{{ redis_volume_data }}:/data"
