---

- hosts: redis_nodes

  vars:

  pre_tasks:

    # - name: "Run pre-tasks"
    #   import_role:
    #     name: pre-tasks

    - name: Install Docker
      import_role:
        name: geerlingguy.docker

  tasks:

    - name: Create redis volume
      docker_volume:
        name: redis_data

    - name: Start redis container
      docker_container:
        name: redis
        image: redis
        command: redis-server --appendonly yes
        state: present
        recreate: yes
        exposed_ports:
          - 6379
        volumes_from:
          - redis_data
