---

- hosts: all

  vars:

    packages: [
      python3-apt,
      python3-pip,
      git,
      sshpass,
      unzip,
      curl,
      apt-transport-https,
      ca-certificates,
      gnupg2,
      software-properties-common,
    ]

    python_modules: [
      { name: docker },
      { name: netaddr },
      { name: python-consul },
    ]

    docker_install_compose: no

  tasks:

    - name: Update host packages
      become: yes
      import_role:
        name: greenthegarden.configure-host
        tasks_from: run-package-update
      run_once: yes
      tags:
        - base
        - update

    - name: Install dependencies
      become: yes
      import_role:
        name: greenthegarden.configure-host
        tasks_from: install-dependencies
      tags:
        - base
        - dependencies

    - name: Install Docker
      become: yes
      import_role:
        name: geerlingguy.docker
      when: ansible_architecture is not search('arm')

    - name: Install Docker for ARM
      become: yes
      import_role:
        name: geerlingguy.docker_arm
      when: ansible_architecture is search('arm')
