---

all:

  hosts:

    controller-node:
      ansible_host: localhost
      ansible_connection: local
    nextcloud-vm:
      # ansible_host: services-node-1
      ansible_host: 172.16.2.101
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
      ansible_ssh_user: vagrant
      consul_node_role: bootstrap

  vars:

    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

    # do not change as used to provision consul on all services_nodes
    consul_group_name: services_nodes

    service_consul_running: no

    # consul_datacenter: nextcloud
    consul_iface: eth1
    consul_bind_address: '172.16.2.101'
    consul_recursors: ['192.168.1.254']
    consul_dnsmasq_servers: ['192.168.1.254', '8.8.8.8', '8.8.4.4']
    consul_join_wan: ['172.16.2.101']
    consul_advertise_address_wan: '172.16.2.101'
    consul_client_address: "{{ ansible_host }}"
    consul_dnsmasq_enable: yes
    consul_connect_enabled: yes
    consul_version: '1.7.2'
    # consul_install_upgrade: yes

  children:

    services_nodes:
      hosts:
        nextcloud-vm:

    redis_instances:
      hosts:
        nextcloud-vm:

    postgres_instances:
      hosts:
        nextcloud-vm:

    nextcloud_instances:
      hosts:
        nextcloud-vm:
