---

all:

  hosts:

    controller-node:
      ansible_host: localhost
      ansible_connection: local
    nextcloud-vm:
      # ansible_host: services-node-1
      ansible_host: 172.16.1.101
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
      ansible_ssh_user: vagrant
      consul_datacenter: nextcloud
      consul_iface: eth1
      consul_node_role: server

  vars:

    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

  children:

    services_nodes:
      hosts:
        nextcloud-vm:
    
    redis_instances:
      hosts:
        nextcloud-vm:

    postgres_instances:
      hosts:
        nextcloud-vm:

    nextcloud_instances:
      hosts:
        nextcloud-vm:
