---

# Ensure all host tasks are performed first, set of common tasks
# - import_playbook: playbooks/base.yml
# Run role to install and set up the Redis on hosts specified as redis_instances
- import_playbook: playbooks/services/redis.yml
# Run role to install and set up Postgres and pgAdmin on hosts specified as postgres_instances
- import_playbook: playbooks/services/postgres.yml
# Run role to install and set up Nextcloud on hosts specified as nextcloud_instances
- import_playbook: playbooks/services/nextcloud.yml
